### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Mengyu2019** [kwahid/C3_sarcopenia_data_descriptor#1]
How to run this project? I didn't find the code.

**Comment by kwahid** [comment]
Hi,

This repo only contains Python code (nifti_conversion_github.ipynb) to generate NIfTI files from TCIA DICOM images and .tag format segmentation files. If you are referring to the code for the deep learning model that used this data, we have not publicly released the model or weights. Please feel free to email me if you have any follow-up questions. 

Best,

Kareem
